name: Dependency & Asset Health

on:
  schedule:
    - cron: '0 3 * * 1' # every Monday 03:00 UTC
  workflow_dispatch:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Depcheck
        run: pnpm health:depcheck
      - name: Placeholder check
        run: pnpm check:placeholders
      - name: Unused images check
        run: pnpm check:images
