name: Drizzle Migrations

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  migrate:
    name: Run DB Migrations
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run Drizzle Migrations
        run: pnpm drizzle-kit push:pg --config=drizzle.config.ts --verify
